### ISSUE TITLE
Milestone 1 Checklist

### ISSUE THREAD

**Issue by dy-lin** [stat545ubc-2020/template-mini-analysis#1]
# Mini Data Analysis Milestone 1 Checklist (30 points)

### Task 1: Choose your favourite dataset (10 points)

- [ ] **Task 1.1:** Choose **4** datasets out of 7 of the `datateachr` package
- [ ] **Task 1.2:** Find out at least **3** attributes about _each_ of 4 datasets using `dplyr` functions
	- Attribute: something such as number of rows, variables, class type...
	- Goal: to have an idea of *what the data looks like*
- [ ] **Task 1.3:** Narrow down the 4 datasets to 2
	- [ ] _Briefly_ explain your choices. What lead you to choose these 2?
- [ ] **Task 1.4:** Narrow down it to 1 dataset!
	- [ ] Think of 1 research question that you would want to answer with _each_ dataset
	- [ ] Note them down, and make a final choice based on what seems more interesting to you

### Task 2: Exploring your dataset (15 points)

- [ ] **Task 2.1:** Complete **4** out of the following 8 exercises:
	- [ ] Plot the distribution of a numeric variable
	- [ ] Create a new variable based on other variables in your data (only if it makes sense)
	- [ ] Investigate how many missing values there are per variable. Can you find a way to plot this?
	- [ ] Explore the relationship between 2 variables in a plot.
	- [ ] Filter observations in your data according to your own criteria. Think of what you'd like to explore - again, if this was the `titanic` dataset, I may want to narrow my search down to passengers born in a particular year...
	- [ ] Use a boxplot to look at the frequency of different observations within a single variable. You can do this for more than one variable if you wish!
	- [ ] Make a new tibble with a subset of your data, with variables and observations that you are interested in exploring.
	- [ ] Use a density plot to explore any of your variables (that are suitable for this type of plot).
- [ ] **Task 2.2:** For the chosen 4 above, provide a _brief_ explanation of why you chose that exercise in relation to your data (in other words, why does it make sense to do that?), and sufficient comments for a reader to understand your reasoning and code

### Task 3: Write your research questions (5 points)

- [ ] Write **4** research questions that you would like to answer with your data and any additional questions

### Task 1: Choose your favourite dataset (10 points)

- [ ] Ask a TA for approval for using your own dataset
- [ ] Write a _brief_ description about your dataset
	- [ ] Describe each variable, etc.
- [ ] Find out at least **3** attributes about your dataset, using `dplyr` functions
	- Attribute: something such as number of rows, variables, class type...
	- Goal: to have an idea of _what the data looks like_

### Task 2: Exploring your dataset (15 points)

- [ ] Task 2.1: Complete **4** out of the following 8 exercises:
	- [ ] Plot the distribution of a numeric variable
	- [ ] Create a new variable based on other variables in your data (only if it makes sense)
	- [ ] Investigate how many missing values there are per variable. Can you find a way to plot this?
	- [ ] Explore the relationship between 2 variables in a plot.
	- [ ] Filter observations in your data according to your own criteria. Think of what you'd like to explore - again, if this was the `titanic` dataset, I may want to narrow my search down to passengers born in a particular year...
	- [ ] Use a boxplot to look at the frequency of different observations within a single variable. You can do this for more than one variable if you wish!
	- [ ] Make a new tibble with a subset of your data, with variables and observations that you are interested in exploring.
	- [ ] Use a density plot to explore any of your variables (that are suitable for this type of plot).
- [ ] Task 2.2: For the chosen 4 above, provide a _brief_ explanation of why you chose that exercise in relation to your data (in other words, why does it make sense to do that?), and sufficient comments for a reader to understand your reasoning and code

### Task 3: Write your research questions (5 points)

- [ ] Write **4** research questions that you would like to answer with your data and any additional questions
