### ISSUE TITLE
Milestone 2 Checklist

### ISSUE THREAD

**Issue by dy-lin** [stat545ubc-2020/template-mini-analysis#4]
# Milestone 2 Criteria (30 pts)

## Task 1 (15 pts)

- [ ] **Task 1.1 (2.5 pts)**: Write out the **4** research from Milestone 1 
- [ ] **Task 1.2 (10 pts)**: Choose **one** task from "summarizing" category and **one** other task from "graphing" category for _each_ of your **4** research questions 

  - [ ] summarizing task for research question 1
  - [ ] graphing task for research question 1
  
  
  - [ ] summarizing task for question 2
  - [ ] graphing task for question 2
  
  
  - [ ] summarizing task for question 3
  - [ ] graphing task for question 3
  
  
  - [ ] summarizing task for question 4
  - [ ] graphing task for question 4
  
	- Here are the tasks for 1.2:
	
	- **Summarizing**:
		- [ ] For one of the categorical variables in your data, compute the:
			- [ ] range
			- [ ] mean
			- [ ] **two** other summary statistics
		- [ ] Compute the number of observations for at least **one** of your categorical variables
			- Do **not** use the function `table()`!
		- [ ] Create a categorical variable with **3** or more groups from an existing numerical variable.
			- You can use this new variable in the other tasks!
			- *An example: age in years into "child, teen, adult, senior"*
		- [ ] Based on **two** categorical variables, calculate **two** summary statistics of your choosing
	- **Graphing**:
		- [ ] Create a graph out of summarized variables that has at least **two** `geom` layers
		- [ ] Create a graph of your choosing:
			- [ ] Make one of the axes logarithmic
			- [ ] Format the axes labels so that they are "pretty" or easier to read
		- [ ] Make a graph where it makes sense to customize the alpha transparency
		- [ ] Create **3** histograms out of summarized variables
			- [ ] Each histogram having different sized bins
			- [ ] Pick the "best" one and explain why it is the best

- [ ] **Task 1.3 (2.5 pts)**: Answer the following questions 
	- [ ] How much closer are you to answering your research questions? 
	- [ ] What aspects of your research questions remain unclear?
	- [ ] Now can your research questions be refined?
	- [ ] Any interesting findings?

## Task 2 (12.5 pts)

- [ ] **Task 2.1 (2.5 pts)**: Can you identify if your data is tidy or untidy?  
	- Go through all your columns, or if you have >8 variables, just pick 8, and 
		- [ ] Explain whether the data is untidy or tidy 
- [ ] **Task 2.2 (5 pts)**: Now, if your data is tidy, untidy it! If it's untidy, then tidy it! 
	- [ ] Be sure to explain your reasoning for this task. Show us the "before" and "after" 
- [ ] **Task 2.3 (5 pts)**: Based on your interest, and your analyses, pick **2** of the 4 research questions to continue your analysis in milestone 3 
	- [ ] Explain your decisions
	- [ ] Save a edited version of your data using 4-8 functions we've covered in this course. Use `saveRDS()`. 

## Reproducibility, Readability, Repo Organization (2.5 pts)

- Reproducibility
	- [ ] Can the TAs run your code without any errors?
	- [ ] Can the TAs knit without any errors?
- Readability
	- [ ] Did you knit your `.Rmd` to a GitHub-friendly format? (e.g. `md_document`, `github_document`)
	- [ ] Did you push this GitHub-friendly report to your repository?
	- [ ] Do you have proper spelling and grammar?
- Repo Organization
	- [ ] Did you remove all duplicate files resulting from merge conflicts?
	- [ ] Are all the files in their corresponding milestone directories?
	- [ ] Did you update your README as the project has progressed?
	- [ ] Did you tag a release for submission?
