### ISSUE TITLE
Milestone 3 Checklist

### ISSUE THREAD

**Issue by dy-lin** [stat545ubc-2020/template-mini-analysis#5]
# Milestone 3 Criteria (40 pts)

Here's a checklist that might help you determine whether you successfully completed Milestone 3.

## Exercise 1: Special Data Types (10 points)

- [ ] Copied over an original plot from a previous milestone
- [ ] First selected task
    - [ ] Produced your new plot or table (3 points)
    - [ ] Provided an explanation (2 points)
- [ ] Second selected task
    - [ ] Produced your new plot or table (3 points)
    - [ ] Provided an explanation (2 points)

    
## Exercise 2: Modelling (10 points)

- [ ] 2.0: You've picked a research question and variable 
- [ ] 2.1: You've stored a model object as a variable, and printed its output to screen (5 points)
- [ ] 2.2:
    - [ ] You've indicated what it is you chose to produce
    - [ ] You've obtained the result using code. 

## Exercise 3: Reading and writing data (10 points)

- [ ] You've made an "output" folder in the top level of your project. 
- [ ] 3.1 (5 points)
    - [ ] You've written code that saves a summary tibble to file
    - [ ] You see the saved csv file in the output folder.
    - [ ] You've used `here::here()`, so that the robustness and reproducibility criteria are satisfied.
- [ ] 3.2 (5 points)
    - [ ] You've written code that saves your model object to file using `saveRDS()`.
    - [ ] You've written code that loads your model object to file using `readRDS()`.
    - [ ] You see the saved rds file in the output folder.
    - [ ] You've used `here::here()`, so that the robustness and reproducibility criteria are satisfied.

## Tidy Repository (10 points)

- [ ] You have a main README file (3 points)
    - [ ] It describes what the project is.
    - [ ] It describes how to engage with the project.
- [ ] File and Folder structure (3 points):
    - [ ] There's a folder for Milestone 1 in the top-level of your project folder.
        - [ ] It has a README file saying briefly what's in this folder. 
        - [ ] This is the only place where Milestone 1 content is found.
    - [ ] There's a folder for Milestone 2 in the top-level of your project folder.
        - [ ] It has a README file saying briefly what's in this folder. 
        - [ ] This is the only place where Milestone 2 content is found.
    - [ ] There's a folder for Milestone 3 in the top-level of your project folder.
        - [ ] It has a README file saying briefly what's in this folder. 
        - [ ] This is the only place where Milestone 3 content is found (except for the things in the `output` folder)
    - [ ] There's an `output` folder in the top-level of your project folder.
        - [ ] It has a README file saying briefly what's in this folder. 
    - [ ] Any other folders in the top-level of your project folder are explained in your main README, if you have any.
        - [ ] These folders have a README file. 
- [ ] Output (2 points)
    - [ ] The milestone 1 Rmd output files are up-to-date and relevant (no relics)
    - [ ] The milestone 2 Rmd output files are up-to-date and relevant (no relics)
    - [ ] The milestone 3 Rmd output files are up-to-date and relevant (no relics)
    - [ ] All data files saved from Exercise 3 appear in the `output` folder. 
- [ ] This Milestone 3 Rmd document knits error-free. (1 point)
- [ ] You've tagged a release for Milestone 3 (1 point)
    - [ ] You've submitted a link to the tagged release on canvas
